[package]
name = "polariton"
version = "0.1.0"
edition = "2024"
resolver = "3"
authors = ["Joel Bondurant"]
description = "A strong coupling of data and visualization."


[dependencies]
iced = { version = "0.14.0", features = ["advanced"] }


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
debug = 0
